parameters:
  - name: DOTNET_SONARQUBE_TOKEN # name of the parameter; required
    type: string # data type of the parameter; required
  - name: SONARQUBE_URL # name of the parameter; required
    type: string # data type of the parameter; required
  - name: SNYK_TOKEN # name of the parameter; required
    type: string # data type of the parameter; required
  - name: SL_TOKEN # name of the parameter; required
    type: string # data type of the parameter; required
  - name: working_directory
    type: string    
  - name: repo
    type: string    
  - name: path
    type: string
  - name: app_name
    type: string    
  - name: csproj
    type: string    

jobs:
  - job: SonarQube
    steps:
      - task: CmdLine@2
        displayName: "Checkout a public GH repo"
        inputs:
          script: |
            git clone https://github.com/ShiftLeftSecurity/shiftleft-csharp-demo && cd shiftleft-csharp-demo/netcoreWebapi                       

      - task: CmdLine@2
        displayName: "Install SonarQube scanner" 
        inputs:
          script: |          
            dotnet tool install --global dotnet-sonarscanner

      - task: CmdLine@2
        displayName: "Build and analyze"
        inputs:
          script: |
            cd ${{ parameters.working_directory }}
            dotnet sonarscanner begin /k:"${{ parameters.app_name }}" /d:sonar.host.url="${{ parameters.SONARQUBE_URL }}" /d:sonar.login="${{ parameters.DOTNET_SONARQUBE_TOKEN }}"     
            dotnet build
            dotnet sonarscanner end /d:sonar.login="${{ parameters.DOTNET_SONARQUBE_TOKEN }}"

  - job: Snyk
    steps:
      - task: CmdLine@2
        displayName: "Checkout a public GH repo"
        inputs:
          script: |
            git clone ${{ parameters.repo }}
      - task: CmdLine@2
        displayName: "Install Snyk CLI"
        inputs:
          script: |
            curl --compressed https://static.snyk.io/cli/latest/snyk-linux -o snyk
            chmod +x ./snyk
            mv ./snyk /usr/local/bin/
      - task: CmdLine@2
        displayName: "Scan .NET code"
        inputs:
          script: |
            cd ${{ parameters.working_directory }}
            dotnet build
            snyk code test --sarif || true
            snyk code test --sarif > $(Build.ArtifactStagingDirectory)/snyk-code.sarif || true
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/snyk-code.sarif"
          ArtifactName: "CodeAnalysisLogs"
          publishLocation: "Container"
  
  - job: SASTScan
    variables:
      SHIFTLEFT_ACCESS_TOKEN: ${{ parameters.SL_TOKEN }}
    steps:
      - task: CmdLine@2
        displayName: "Checkout a public GH repo"
        inputs:
          script: |
            git clone ${{ parameters.repo }}
      - task: CmdLine@2
        displayName: "Install sast-scan CLI"
        inputs:
          script: |
            curl https://cdn.shiftleft.io/download/sl >/usr/local/bin/sl && chmod a+rx /usr/local/bin/sl
      - task: CmdLine@2
        displayName: "Scan .NET code"
        inputs:
          script: |
            cd ${{ parameters.working_directory }}
            dotnet build
            sl analyze --app ${{ parameters.app_name }} --csharp --wait ${{ parameters.csproj }}
