name: Code scans

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - .github/**
      - README.md

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - .github/**
      - README.md

pool:
  vmImage: ubuntu-latest

jobs:
  # - template: "/.ado/templates/scan-dotnet-code.yml"
    # parameters:    
    #   SNYK_TOKEN: $(SNYK_TOKEN)
    #   SL_TOKEN: $(SL_TOKEN)
    #   repo: 'https://github.com/ShiftLeftSecurity/shiftleft-csharp-demo'
    #   working_directory: 'shiftleft-csharp-demo/netcoreWebapi'
    #   path: 'shiftleft-csharp-demo'
    #   app_name: 'shiftleft-csharp-demo'
    #   csproj: 'netcoreWebapi.csproj'
  - job: SonarQube
    steps:
      - task: CmdLine@2
        displayName: "Checkout a public GH repo"
        inputs:
          script: |
            git clone https://github.com/ShiftLeftSecurity/shiftleft-csharp-demo && cd shiftleft-csharp-demo/netcoreWebapi                       

      - task: SonarQubePrepare@5
        inputs:
          SonarQube: 'SonarQubeDotNetExample'
          scannerMode: 'MSBuild'
          projectKey: 'shiftleft-csharp-demo'
          projectName: 'shiftleft-csharp-demo'
          extraProperties: |
            # Additional properties that will be passed to the scanner, 
            # Put one key=value per line, example:
            # sonar.exclusions=**/*.bin
            sonar.projectBaseDir=shiftleft-csharp-demo/netcoreWebapi

      - task: CmdLine@2
        displayName: "Build code"
        inputs:
          script: |
            cd shiftleft-csharp-demo/netcoreWebapi
            dotnet build 
      - task: SonarQubeAnalyze@5
        inputs:
          jdkversion: 'JAVA_HOME_11_X64'