name: Code scans

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - .github/**
      - README.md

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - .github/**
      - README.md

pool:
  vmImage: ubuntu-latest

jobs:
  - template: "/.ado/templates/scan-dotnet-code.yml"
    parameters:
      DOTNET_SONARQUBE_TOKEN: $(DOTNET_SONARQUBE_TOKEN)
      SONARQUBE_URL: $(SONARQUBE_CODESPACES_URL)
      SNYK_TOKEN: $(SNYK_TOKEN)
      SL_TOKEN: $(SL_TOKEN)
      repo: 'https://github.com/ShiftLeftSecurity/shiftleft-csharp-demo'
      working_directory: 'shiftleft-csharp-demo/netcoreWebapi'
      path: 'shiftleft-csharp-demo'
      app_name: 'shiftleft-csharp-demo'
      csproj: 'netcoreWebapi.csproj'
  - template: "/.ado/templates/scan-java-code.yml"
    parameters:
      JAVA_SONARQUBE_TOKEN: $(JAVA_SONARQUBE_TOKEN)
      SONARQUBE_URL: $(SONARQUBE_CODESPACES_URL)
      SNYK_TOKEN: $(SNYK_TOKEN)
      SL_TOKEN: $(SL_TOKEN)
      repo: 'https://github.com/ShiftLeftSecurity/shiftleft-java-demo'
      working_directory: 'shiftleft-java-demo'
      path: 'shiftleft-java-demo'
      app_name: 'shiftleft-java-demo'
      jar: 'target/*.jar'
  - template: "/.ado/templates/scan-go-code.yml"
    parameters:
      GO_SONARQUBE_TOKEN: $(GO_SONARQUBE_TOKEN)
      SONARQUBE_URL: $(SONARQUBE_CODESPACES_URL)
      SNYK_TOKEN: $(SNYK_TOKEN)
      SL_TOKEN: $(SL_TOKEN)
      repo: 'https://github.com/ShiftLeftSecurity/shiftleft-go-demo'
      working_directory: 'shiftleft-go-demo'
      path: 'shiftleft-go-demo'
      app_name: 'shiftleft-go-example'
  - template: "/.ado/templates/scan-python-code.yml"
    parameters:
      GO_SONARQUBE_TOKEN: $(PYTHON_SONARQUBE_TOKEN)
      SONARQUBE_URL: $(SONARQUBE_CODESPACES_URL)
      SNYK_TOKEN: $(SNYK_TOKEN)
      SL_TOKEN: $(SL_TOKEN)
      repo: 'https://github.com/ShiftLeftSecurity/shiftleft-python-demo'
      working_directory: 'shiftleft-python-demo'
      path: 'shiftleft-python-demo'
      app_name: 'shiftleft-python-demo'