name: Code scans

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".ado/**"
      - "steps.sh"
      - ".gitignore"
      - "README.md"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  dotnet:
    permissions:
      contents: read
      security-events: write
    uses: 0GiS0/scan-code-vulnerabilities/.github/workflows/scan-dotnet-code.yaml@main
    with:
      app-name: 'shiftleft-csharp-demo'
      repo: 'ShiftLeftSecurity/shiftleft-csharp-demo'
      path: 'shiftleft-csharp-demo'
      working-directory: 'shiftleft-csharp-demo/netcoreWebapi'
      csproj: 'netcoreWebapi.csproj'
    secrets:
      SL_TOKEN: ${{ secrets.SL_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      DOTNET_SONARQUBE_TOKEN: ${{ secrets.DOTNET_SONARQUBE_TOKEN }}
      SONARQUBE_CODESPACES_URL: ${{ secrets.SONARQUBE_CODESPACES_URL }}
  go:
    needs: dotnet
    permissions:
      contents: read
      security-events: write
    uses: 0GiS0/scan-code-vulnerabilities/.github/workflows/scan-go-code.yaml@main
    with:
      app-name: 'shiftleft-go-example'
      repo: 'ShiftLeftSecurity/shiftleft-go-demo'
      path: 'shiftleft-go-demo'
      working-directory: 'shiftleft-go-demo'
    secrets:
      SL_TOKEN: ${{ secrets.SL_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      GO_SONARQUBE_TOKEN: ${{ secrets.GO_SONARQUBE_TOKEN }}
      SONARQUBE_CODESPACES_URL: ${{ secrets.SONARQUBE_CODESPACES_URL }}
  java:
    needs: go
    permissions:
      contents: read
      security-events: write
    uses: 0GiS0/scan-code-vulnerabilities/.github/workflows/scan-java-code.yaml@main
    with:
      app-name: 'shiftleft-java-demo'
      repo: 'ShiftLeftSecurity/shiftleft-java-demo'
      path: 'shiftleft-java-demo'
      working-directory: 'shiftleft-java-demo'
    secrets:
      SL_TOKEN: ${{ secrets.SL_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      JAVA_SONARQUBE_TOKEN: ${{ secrets.JAVA_SONARQUBE_TOKEN }}
      SONARQUBE_CODESPACES_URL: ${{ secrets.SONARQUBE_CODESPACES_URL }}
  python:
    needs: java
    permissions:
      contents: read
      security-events: write
    uses: 0GiS0/scan-code-vulnerabilities/.github/workflows/scan-python-code.yaml@main
    with:
      app-name: 'shiftleft-python-demo'
      repo: 'ShiftLeftSecurity/shiftleft-python-demo'
      path: 'shiftleft-python-demo'
      working-directory: 'shiftleft-python-demo'
    secrets:
      SL_TOKEN: ${{ secrets.SL_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      PYTHON_SONARQUBE_TOKEN: ${{ secrets.PYTHON_SONARQUBE_TOKEN }}
      SONARQUBE_CODESPACES_URL: ${{ secrets.SONARQUBE_CODESPACES_URL }}