name: Scan Java Code

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".ado/**"
      - "README.md"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonarqube:
    name: Sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v4
        with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
          repository: 'ShiftLeftSecurity/shiftleft-java-demo'
          path: 'shiftleft-csharp-demo'      
      - name: Install SonarQube scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |          
          dotnet tool install --global dotnet-sonarscanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        shell: powershell
        run: |
          cd shiftleft-csharp-demo/netcoreWebapi
          dotnet sonarscanner begin /k:"shiftleft-java-demo" /d:sonar.host.url="${{ secrets.SONARQUBE_CODESPACES_URL }}" /d:sonar.login="${{ secrets.JAVA_SONARQUBE_TOKEN }}"     
          dotnet build
          dotnet sonarscanner end /d:sonar.login="${{ secrets.JAVA_SONARQUBE_TOKEN }}"
  snyk:
    name: Snyk
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    permissions:
      contents: read
      security-events: write      
    steps:
      - uses: actions/checkout@v4
        with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
          repository: 'ShiftLeftSecurity/shiftleft-java-demo'
          path: 'shiftleft-java-demo'
      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
              
      - name: Snyk Code test and report
        continue-on-error: true       
        run: |
            cd shiftleft-java-demo
            mvn clean package
            snyk code test --sarif || true
            snyk code test --sarif  > snyk-code.sarif

      # Push the Snyk Code results into GitHub Code Scanning tab
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: shiftleft-java-demo/snyk-code.sarif  

  sast-scan:
    name: Sast-scan
    runs-on: ubuntu-latest
    env:
      SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SL_TOKEN }}
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:        
          repository: 'ShiftLeftSecurity/shiftleft-java-demo'
          path: 'shiftleft-java-demo'
      - name: Install sast-scan
        run: |
          curl https://cdn.shiftleft.io/download/sl >/usr/local/bin/sl && chmod a+rx /usr/local/bin/sl
      - name: Perform Scan
        run: |
          cd shiftleft-java-demo
          mvn clean package
          sl analyze --app shiftleft-java-demo --csharp --wait netcoreWebapi.csproj
        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SL_TOKEN }}
      - name: Get SARIF
        continue-on-error: true
        run: |
          docker run --rm -e "WORKSPACE=${PWD}" -v $PWD:/app shiftleft/scan scan --src /app --out_dir /app/reports

      - name: Check reports
        run: |
          ls reports
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: reports/
